"""First-class deterministic security-property registry.

The semantic heart of HORCRUX. Modeled around security properties, never
around scanner names. Each property declares its full contract: required
evidence, test methods, asset types, prerequisites, oracle, thresholds,
confirmation/refutation/blocked conditions, severity model, remediation.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class SecurityProperty(BaseModel):
    property_id: str
    category: str
    title: str
    required_evidence: list[str] = Field(default_factory=list)
    test_methods: list[str] = Field(default_factory=list)
    required_asset_types: list[str] = Field(default_factory=list)
    prerequisites: list[str] = Field(default_factory=list)
    oracle: str = ""
    min_evidence_threshold: int = 2
    confirmation_conditions: list[str] = Field(default_factory=list)
    refutation_conditions: list[str] = Field(default_factory=list)
    blocked_conditions: list[str] = Field(default_factory=list)
    severity: str = "medium"
    remediation: str = ""


def _p(pid: str, cat: str, title: str, **kw) -> SecurityProperty:
    return SecurityProperty(property_id=pid, category=cat, title=title, **kw)


PROPERTIES: list[SecurityProperty] = [
    # ── AUTHENTICATION ──────────────────────────────────────────────
    _p("AUTHN_UNAUTH_PROTECTED_ACCESS", "authentication",
       "Unauthenticated access to protected function",
       required_evidence=["baseline_anon", "auth_requirement", "anon_response"],
       test_methods=["http_probe:anonymous"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="authn_unauth_oracle",
       confirmation_conditions=["anon 200 with protected content", "no auth challenge"],
       refutation_conditions=["anon 401/403/login redirect"],
       blocked_conditions=["target unreachable"],
       severity="high", remediation="Enforce authentication on the endpoint."),
    _p("AUTHN_BYPASS", "authentication", "Authentication bypass",
       required_evidence=["baseline_auth", "bypass_mutation", "differential"],
       test_methods=["auth_probe", "http_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="authn_bypass_oracle",
       confirmation_conditions=["restricted content without valid credential"],
       refutation_conditions=["bypass rejected 401/403"],
       blocked_conditions=["no credential material"], severity="critical",
       remediation="Fix server-side authentication checks."),
    _p("AUTHN_SESSION_FIXATION", "authentication", "Session fixation",
       required_evidence=["session_id", "login_transition", "session_reuse"],
       test_methods=["http_probe:session"], required_asset_types=["endpoint"],
       prerequisites=["web_target", "login_endpoint"], oracle="session_fixation_oracle",
       confirmation_conditions=["pre-login session accepted post-login"],
       refutation_conditions=["session rotated at login"],
       blocked_conditions=["no session mechanism observed"], severity="medium",
       remediation="Rotate session identifiers at authentication."),
    _p("AUTHN_WEAK_BEHAVIOR", "authentication", "Weak authentication behavior",
       required_evidence=["login_endpoint", "credential_mutation", "differential"],
       test_methods=["auth_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="authn_weak_oracle",
       confirmation_conditions=["user enumeration / no lockout / weak policy proven"],
       refutation_conditions=["uniform responses + lockout"],
       blocked_conditions=["no login surface"], severity="medium",
       remediation="Harden authentication responses and lockout."),
    _p("AUTHN_CREDENTIAL_EXPOSURE", "authentication", "Credential exposure",
       required_evidence=["response_body", "secret_pattern", "reachability"],
       test_methods=["http_probe", "endpoint_validate"], required_asset_types=["endpoint", "response"],
       prerequisites=["web_target"], oracle="secret_exposure_oracle",
       confirmation_conditions=["credential/secret pattern in reachable response, non-HTML config"],
       refutation_conditions=["no secret pattern / HTML error only"],
       blocked_conditions=["target unreachable"], severity="high",
       remediation="Remove secrets from responses; rotate exposed credentials."),
    # ── AUTHORIZATION ───────────────────────────────────────────────
    _p("AUTHZ_BOLA_IDOR", "authorization", "BOLA / IDOR",
       required_evidence=["object_instance", "owner_evidence", "cross_identity_differential"],
       test_methods=["authz_compare"], required_asset_types=["endpoint", "object"],
       prerequisites=["web_target", "two_identities", "object_instance"],
       oracle="bola_oracle",
       confirmation_conditions=["identity A reads object owned by B, private fields returned"],
       refutation_conditions=["403/404 uniform", "public catalog object"],
       blocked_conditions=["second identity unavailable", "no object instance"],
       severity="high", remediation="Enforce per-object ownership checks."),
    _p("AUTHZ_HORIZONTAL", "authorization", "Horizontal authorization failure",
       required_evidence=["object_instance", "two_identities", "differential"],
       test_methods=["authz_compare"], required_asset_types=["endpoint", "object"],
       prerequisites=["two_identities"], oracle="bola_oracle",
       confirmation_conditions=["peer object readable across identities"],
       refutation_conditions=["uniform denial"], blocked_conditions=["second identity unavailable"],
       severity="high", remediation="Scope object access to owner."),
    _p("AUTHZ_VERTICAL_PRIVESC", "authorization", "Vertical privilege escalation",
       required_evidence=["privileged_endpoint", "low_priv_differential"],
       test_methods=["authz_compare", "http_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="vertical_oracle",
       confirmation_conditions=["low-priv/anon reaches admin operation with 200 + privileged content"],
       refutation_conditions=["401/403 for low-priv"], blocked_conditions=["no privileged surface"],
       severity="high", remediation="Enforce role checks on privileged operations."),
    _p("AUTHZ_FUNCTION_LEVEL", "authorization", "Function-level authorization failure",
       required_evidence=["restricted_function", "differential"],
       test_methods=["authz_compare", "http_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="vertical_oracle",
       confirmation_conditions=["restricted function executable by unauthorized actor"],
       refutation_conditions=["uniform denial"], blocked_conditions=["no restricted function"],
       severity="high", remediation="Authorize every sensitive function server-side."),
    _p("AUTHZ_TENANT_ISOLATION", "authorization", "Tenant isolation failure",
       required_evidence=["tenant_object", "cross_tenant_differential"],
       test_methods=["authz_compare"], required_asset_types=["endpoint", "object"],
       prerequisites=["two_identities", "tenant_context"], oracle="bola_oracle",
       confirmation_conditions=["tenant A reads tenant B object"],
       refutation_conditions=["tenant-scoped denial"], blocked_conditions=["single tenant only"],
       severity="high", remediation="Isolate tenant data access."),
    # ── INPUT VALIDATION ────────────────────────────────────────────
    _p("INJECT_SQL", "input_validation", "SQL injection",
       required_evidence=["baseline", "mutation", "db_error_or_time_differential", "repeatability"],
       test_methods=["sqli_probe", "param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="sqli_oracle",
       min_evidence_threshold=3,
       confirmation_conditions=["DB/framework error signature or stable time differential on mutation vs baseline"],
       refutation_conditions=["neutral/sanitized across payload classes"],
       blocked_conditions=["parameter not executable"], severity="critical",
       remediation="Use parameterized queries."),
    _p("INJECT_NOSQL", "input_validation", "NoSQL injection",
       required_evidence=["baseline", "mutation", "differential"],
       test_methods=["sqli_probe", "param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="nosql_oracle",
       confirmation_conditions=["operator-injection alters result set / error differential"],
       refutation_conditions=["neutral"], blocked_conditions=["parameter not executable"],
       severity="high", remediation="Validate and type-check NoSQL query input."),
    _p("INJECT_COMMAND", "input_validation", "Command injection",
       required_evidence=["baseline", "separator_mutation", "output_reflection"],
       test_methods=["cmdi_probe", "param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="cmdi_oracle",
       confirmation_conditions=["command output reflected (uid=/whoami/marker)"],
       refutation_conditions=["neutral"], blocked_conditions=["parameter not executable"],
       severity="critical", remediation="Avoid shell invocation; allowlist input."),
    _p("INJECT_TEMPLATE", "input_validation", "Template injection",
       required_evidence=["baseline", "template_marker", "evaluation_differential"],
       test_methods=["param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="ssti_oracle",
       confirmation_conditions=["template expression evaluated (7*7=49 marker)"],
       refutation_conditions=["verbatim reflection / escaped"], blocked_conditions=["parameter not executable"],
       severity="high", remediation="Never render untrusted input as template."),
    _p("INJECT_LDAP", "input_validation", "LDAP injection",
       required_evidence=["baseline", "ldap_meta_mutation", "differential"],
       test_methods=["param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="ldap_oracle",
       confirmation_conditions=["filter-semantics change / LDAP error differential"],
       refutation_conditions=["neutral"], blocked_conditions=["parameter not executable"],
       severity="high", remediation="Escape LDAP filter input."),
    _p("INJECT_XPATH", "input_validation", "XPath injection",
       required_evidence=["baseline", "xpath_mutation", "differential"],
       test_methods=["param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="xpath_oracle",
       confirmation_conditions=["query-semantics change / XPath error"],
       refutation_conditions=["neutral"], blocked_conditions=["parameter not executable"],
       severity="high", remediation="Parameterize XPath queries."),
    # ── OUTPUT / CLIENT ─────────────────────────────────────────────
    _p("XSS_REFLECTED", "output_client", "Reflected XSS",
       required_evidence=["injection", "reflection", "unescaped_context"],
       test_methods=["xss_probe", "param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="xss_oracle",
       confirmation_conditions=["unescaped reflection in executable context"],
       refutation_conditions=["escaped/absent reflection"], blocked_conditions=["parameter not executable"],
       severity="high", remediation="Context-aware output encoding."),
    _p("XSS_STORED", "output_client", "Stored XSS",
       required_evidence=["injection", "persistence", "retrieval_reflection", "unescaped_context"],
       test_methods=["xss_probe:stored"], required_asset_types=["parameter", "endpoint"],
       prerequisites=["web_target", "owned_parameter", "read_endpoint"], oracle="xss_stored_oracle",
       min_evidence_threshold=4,
       confirmation_conditions=["payload persists and reflects unescaped on retrieval"],
       refutation_conditions=["not persisted / escaped"], blocked_conditions=["no write+read pair"],
       severity="high", remediation="Encode stored content on output; validate on input."),
    _p("XSS_DOM", "output_client", "DOM XSS sink",
       required_evidence=["js_sink", "tainted_flow", "sink_evidence"],
       test_methods=["js_analyze"], required_asset_types=["response", "endpoint"],
       prerequisites=["js_bundle"], oracle="dom_oracle",
       confirmation_conditions=["dangerous sink with attacker-controllable source"],
       refutation_conditions=["no sink / safe sink"], blocked_conditions=["no JS"],
       severity="medium", remediation="Use safe DOM APIs."),
    _p("OPEN_REDIRECT", "output_client", "Open redirect",
       required_evidence=["redirect_param", "controlled_target", "external_resolution"],
       test_methods=["http_probe"], required_asset_types=["parameter", "endpoint"],
       prerequisites=["web_target", "owned_parameter"], oracle="redirect_oracle",
       confirmation_conditions=["attacker URL honored in Location (external)"],
       refutation_conditions=["relative/allowlisted only"], blocked_conditions=["no redirect surface"],
       severity="medium", remediation="Allowlist redirect targets."),
    # ── FILE / PATH ─────────────────────────────────────────────────
    _p("PATH_TRAVERSAL", "file_path", "Path traversal / arbitrary file read",
       required_evidence=["baseline", "traversal_mutation", "fs_marker", "repeatability"],
       test_methods=["traversal_probe", "param_fuzz"], required_asset_types=["parameter", "endpoint"],
       prerequisites=["web_target"], oracle="traversal_oracle",
       confirmation_conditions=["filesystem marker (passwd/shadow/win.ini markers) in response, stable repeat"],
       refutation_conditions=["neutral"], blocked_conditions=["no file surface"],
       severity="high", remediation="Canonicalize and confine file paths."),
    _p("FILE_UPLOAD_WEAKNESS", "file_path", "Insecure file upload",
       required_evidence=["upload_surface", "executable_upload", "retrieval"],
       test_methods=["upload_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target", "upload_surface"], oracle="upload_oracle",
       confirmation_conditions=["executable content stored and retrievable"],
       refutation_conditions=["rejected/sanitized"], blocked_conditions=["no upload surface"],
       severity="high", remediation="Validate type/content, store outside webroot."),
    # ── SSRF ────────────────────────────────────────────────────────
    _p("SSRF_BASIC", "ssrf", "Server-side request forgery",
       required_evidence=["controlled_url", "fetch_differential", "network_evidence"],
       test_methods=["ssrf_probe", "param_fuzz"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="ssrf_oracle",
       confirmation_conditions=["server fetched controlled host (DNS/interaction or internal response)"],
       refutation_conditions=["no fetch / reflection only"], blocked_conditions=["no URL surface"],
       severity="high", remediation="Allowlist egress; disable URL fetching from input."),
    _p("SSRF_INTERNAL", "ssrf", "SSRF to internal service",
       required_evidence=["controlled_url", "internal_target", "internal_response"],
       test_methods=["ssrf_probe"], required_asset_types=["parameter"],
       prerequisites=["web_target", "owned_parameter"], oracle="ssrf_oracle",
       confirmation_conditions=["internal/metadata response disclosed"],
       refutation_conditions=["blocked/neutral"], blocked_conditions=["no URL surface"],
       severity="critical", remediation="Block internal/metadata egress."),
    # ── API ─────────────────────────────────────────────────────────
    _p("API_EXCESSIVE_DATA", "api", "Excessive data exposure",
       required_evidence=["anonymous_or_lowpriv_request", "response_schema", "sensitive_fields"],
       test_methods=["api_probe"], required_asset_types=["endpoint", "response"],
       prerequisites=["web_target"], oracle="excessive_data_oracle",
       confirmation_conditions=["sensitive fields (password hash/token/role/internal) returned to unauthorized actor"],
       refutation_conditions=["minimal schema only"], blocked_conditions=["endpoint unreachable"],
       severity="medium", remediation="Minimize response schemas per actor."),
    _p("API_MASS_ASSIGNMENT", "api", "Mass assignment",
       required_evidence=["writable_schema", "privileged_field_mutation", "persistence"],
       test_methods=["api_probe"], required_asset_types=["endpoint", "parameter"],
       prerequisites=["web_target", "mutation_endpoint"], oracle="mass_assignment_oracle",
       confirmation_conditions=["privileged field (role/admin) accepted and persisted"],
       refutation_conditions=["ignored/rejected"], blocked_conditions=["no mutation surface"],
       severity="high", remediation="Allowlist writable fields server-side."),
    _p("API_METHOD_AUTH", "api", "Improper method authorization",
       required_evidence=["method_matrix", "differential"],
       test_methods=["api_probe", "http_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="method_auth_oracle",
       confirmation_conditions=["privileged method accepted for unauthorized actor"],
       refutation_conditions=["uniform denial"], blocked_conditions=["endpoint unreachable"],
       severity="medium", remediation="Authorize every method."),
    _p("API_UNDOC_SENSITIVE", "api", "Undocumented sensitive endpoint",
       required_evidence=["discovered_route", "live_confirmation", "sensitivity"],
       test_methods=["http_probe", "endpoint_validate"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="undoc_endpoint_oracle",
       confirmation_conditions=["live sensitive endpoint outside documented surface"],
       refutation_conditions=["non-sensitive / unreachable"], blocked_conditions=["no discovery"],
       severity="medium", remediation="Inventory and authorize all endpoints."),
    _p("API_STATE_TRANSITION", "api", "Unsafe state transition",
       required_evidence=["workflow_model", "transition_mutation", "invariant_violation"],
       test_methods=["workflow_probe"], required_asset_types=["workflow", "endpoint"],
       prerequisites=["workflow_model"], oracle="workflow_oracle",
       confirmation_conditions=["skipped/reordered/tampered transition accepted"],
       refutation_conditions=["enforced"], blocked_conditions=["no workflow"],
       severity="medium", remediation="Validate state transitions server-side."),
    # ── SESSION / STATE ─────────────────────────────────────────────
    _p("SESSION_INVALIDATION", "session", "Session invalidation failure",
       required_evidence=["session", "logout_transition", "reuse_probe"],
       test_methods=["http_probe:session"], required_asset_types=["endpoint"],
       prerequisites=["session"], oracle="session_invalidation_oracle",
       confirmation_conditions=["session usable after logout"],
       refutation_conditions=["invalidated"], blocked_conditions=["no session"],
       severity="medium", remediation="Invalidate sessions on logout."),
    _p("SESSION_TOKEN_EXPOSURE", "session", "Token exposure",
       required_evidence=["response_or_url", "token_pattern", "reachability"],
       test_methods=["http_probe"], required_asset_types=["response", "endpoint"],
       prerequisites=["web_target"], oracle="secret_exposure_oracle",
       confirmation_conditions=["token in URL/log/client response reachable"],
       refutation_conditions=["no token"], blocked_conditions=["no auth surface"],
       severity="medium", remediation="Keep tokens out of URLs/logs."),
    # ── BUSINESS LOGIC ──────────────────────────────────────────────
    _p("BIZ_WORKFLOW_BYPASS", "business_logic", "Workflow bypass",
       required_evidence=["workflow_model", "omitted_step", "acceptance"],
       test_methods=["workflow_probe"], required_asset_types=["workflow", "endpoint"],
       prerequisites=["workflow_model"], oracle="workflow_oracle",
       confirmation_conditions=["required step omitted yet flow completes"],
       refutation_conditions=["rejected"], blocked_conditions=["no workflow"],
       severity="medium", remediation="Enforce step preconditions."),
    _p("BIZ_QUANTITY_MANIPULATION", "business_logic", "Quantity manipulation",
       required_evidence=["workflow_model", "quantity_mutation", "total_differential"],
       test_methods=["workflow_probe"], required_asset_types=["workflow", "parameter"],
       prerequisites=["workflow_model"], oracle="quantity_oracle",
       confirmation_conditions=["negative/zero quantity alters total"],
       refutation_conditions=["validated"], blocked_conditions=["no workflow"],
       severity="medium", remediation="Validate quantities server-side."),
    _p("BIZ_PRICE_MANIPULATION", "business_logic", "Price manipulation",
       required_evidence=["workflow_model", "price_mutation", "acceptance"],
       test_methods=["workflow_probe"], required_asset_types=["workflow", "parameter"],
       prerequisites=["workflow_model"], oracle="price_oracle",
       confirmation_conditions=["client-supplied price accepted"],
       refutation_conditions=["server-side pricing"], blocked_conditions=["no workflow"],
       severity="high", remediation="Never trust client prices."),
    # ── CONFIGURATION ───────────────────────────────────────────────
    _p("CONFIG_DIR_LISTING", "configuration", "Directory listing",
       required_evidence=["index_markers", "file_entries"],
       test_methods=["http_probe", "endpoint_validate"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="dir_listing_oracle",
       confirmation_conditions=["index markers + file entries on live endpoint"],
       refutation_conditions=["no markers"], blocked_conditions=["endpoint unreachable"],
       severity="medium", remediation="Disable directory indexing."),
    _p("CONFIG_ADMIN_EXPOSURE", "configuration", "Exposed administrative interface",
       required_evidence=["admin_surface", "admin_markers", "access_context"],
       test_methods=["http_probe"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="admin_surface_oracle",
       confirmation_conditions=["admin markers reachable by unauthorized actor"],
       refutation_conditions=["401/403 enforced"], blocked_conditions=["no admin surface"],
       severity="medium", remediation="Restrict admin interfaces."),
    _p("CONFIG_DEBUG_EXPOSURE", "configuration", "Debug/error disclosure",
       required_evidence=["error_response", "diagnostic_markers"],
       test_methods=["http_probe"], required_asset_types=["endpoint", "response"],
       prerequisites=["web_target"], oracle="debug_oracle",
       confirmation_conditions=["stack trace/paths/config in error output"],
       refutation_conditions=["generic error page"], blocked_conditions=["endpoint unreachable"],
       severity="low", remediation="Use generic error pages."),
    _p("CONFIG_BACKUP_EXPOSURE", "configuration", "Backup/configuration exposure",
       required_evidence=["artifact_response", "format_markers"],
       test_methods=["http_probe", "endpoint_validate"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="backup_oracle",
       confirmation_conditions=["valid backup/config syntax (env/SQL/git) on live endpoint"],
       refutation_conditions=["HTML/catchall only"], blocked_conditions=["endpoint unreachable"],
       severity="high", remediation="Remove backup/config artifacts from webroot."),
    _p("CONFIG_CORS", "configuration", "CORS misconfiguration",
       required_evidence=["cors_probe", "reflective_origin_with_credentials"],
       test_methods=["http_probe:cors"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="cors_oracle",
       confirmation_conditions=["arbitrary origin reflected with credentials"],
       refutation_conditions=["strict allowlist / no credentials"], blocked_conditions=["endpoint unreachable"],
       severity="medium", remediation="Restrict allowed origins; avoid credentials wildcard."),
    _p("CONFIG_HEADERS", "configuration", "Security-header deficiencies",
       required_evidence=["response_headers", "missing_set"],
       test_methods=["http_probe:headers"], required_asset_types=["endpoint"],
       prerequisites=["web_target"], oracle="headers_oracle",
       confirmation_conditions=["multiple critical headers absent on live endpoint"],
       refutation_conditions=["headers present"], blocked_conditions=["endpoint unreachable"],
       severity="low", remediation="Set baseline security headers."),
    # ── GRAPHQL ─────────────────────────────────────────────────────
    _p("GRAPHQL_INTROSPECTION", "graphql", "GraphQL introspection exposure",
       required_evidence=["graphql_endpoint", "introspection_response", "schema_types"],
       test_methods=["graphql_probe"], required_asset_types=["endpoint"],
       prerequisites=["graphql_endpoint"], oracle="graphql_intro_oracle",
       confirmation_conditions=["full schema disclosed via introspection"],
       refutation_conditions=["disabled"], blocked_conditions=["no graphql"],
       severity="low", remediation="Disable introspection in production."),
    _p("GRAPHQL_AUTHZ", "graphql", "GraphQL field/object authorization failure",
       required_evidence=["graphql_operation", "cross_identity_differential"],
       test_methods=["graphql_probe", "authz_compare"], required_asset_types=["endpoint", "object"],
       prerequisites=["graphql_endpoint", "two_identities"], oracle="graphql_authz_oracle",
       confirmation_conditions=["unauthorized field/object access"],
       refutation_conditions=["enforced"], blocked_conditions=["no graphql / second identity unavailable"],
       severity="high", remediation="Authorize every GraphQL field/object."),
    # ── INFRASTRUCTURE ──────────────────────────────────────────────
    _p("INFRA_EXPOSED_SERVICE", "infrastructure", "Exposed sensitive service",
       required_evidence=["open_port", "service_banner", "sensitivity"],
       test_methods=["service_enum"], required_asset_types=["service"],
       prerequisites=["network"], oracle="exposed_service_oracle",
       confirmation_conditions=["sensitive service reachable without auth (DB/Redis/SMB-anon)"],
       refutation_conditions=["auth required / filtered"], blocked_conditions=["host unreachable"],
       severity="high", remediation="Restrict service exposure; require auth."),
    _p("INFRA_KNOWN_VULN_COMPONENT", "infrastructure", "Known vulnerable component",
       required_evidence=["product", "version", "cpe_or_intel_match", "service_confirmed"],
       test_methods=["cve_correlation"], required_asset_types=["service"],
       prerequisites=["versioned_software"], oracle="known_vuln_oracle",
       confirmation_conditions=["versioned product + intel match on confirmed service"],
       refutation_conditions=["no match / version mismatch"], blocked_conditions=["no version evidence"],
       severity="high", remediation="Patch or upgrade the component."),
]

REGISTRY: dict[str, SecurityProperty] = {p.property_id: p for p in PROPERTIES}


def get_property(pid: str) -> SecurityProperty | None:
    return REGISTRY.get(pid)


def properties_for_category(category: str) -> list[SecurityProperty]:
    return [p for p in PROPERTIES if p.category == category]


def all_property_ids() -> list[str]:
    return sorted(REGISTRY)
